import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import NextAuthProvider from "./Providers/NextAuthProvider";
import Navbar from "../../Components/Navber";
import NextAuthProvider from "./Providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";
import Footer from "../../Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "QuickNCart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <Toaster position="top-center" reverseOrder={false}/>
          <Navbar/>
          {children} 
          <Footer/>
          </NextAuthProvider>
      </body>
    </html>
  );
}
